### PR TITLE
Add property helper function

### LINKED ISSUE #17: Generic interface to get property values
We should add a member function to `Property` that evaluates the property at a given dependent variable value, independent of how the property is stored (i.e. scalar value, polynomial, table).

### PR DESCRIPTION
**Pull request by streeve**
Closes #17

### CODE REVIEW

**Comment by streeve** [comment]
@hespuck19 can you take a look at this? Hopefully useful in a number of places

**Comment by hespuck19** [comment]
> @hespuck19 can you take a look at this? Hopefully useful in a number of places

Definitely looks helpful! I think there may be one section where I don't want to evaluate Laurent polynomials but I think the way its setup now should still work with the changes you suggested there.

**Review by hespuck19 — APPROVED** [review]

**Comment by streeve** [comment]
Looks like I broke all the tests, do you have time to look more at this, @hespuck19? There's also many more places this function could be used (once it actually works of course)

**Comment by hespuck19** [comment]
> Looks like I broke all the tests, do you have time to look more at this, @hespuck19? There's also many more places this function could be used (once it actually works of course)

I'll make a new branch and try to implement something that (maybe, hopefully) doesn't break the tests.

**Review by hespuck19 — APPROVED** [review]

**Pull request merged**
